const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const answerSchema = new Schema({
  title: String,
  Q1: String,
  L1: String,
  R1: String,
  Q2: String,
  L2: String,
  R2: String,
  Q3: String,
  L3: String,
  R3: String,
  Q4: String,
  L4: String,
  R4: String,
  Q5: String,
  L5: String,
  R5: String,
  Q6: String,
  L6: String,
  R6: String,
  Q7: String,
  L7: String,
  R7: String,
  Q8: String,
  L8: String,
  R8: String,
  Q9: String,
  L9: String,
  R9: String,
  Q10: String,
  L10: String,
  R10: String,
  Q11: String,
  L11: String,
  R11: String,
  Q12: String,
  L12: String,
  R12: String,
  a_1: Number,
  b_1: Number,
  a_2: Number,
  b_2: Number,
  a_3: Number,
  b_3: Number,
  a_4: Number,
  b_4: Number,
  a_5: Number,
  b_5: Number,
  a_6: Number,
  b_6: Number,
  a_7: Number,
  b_7: Number,
  a_8: Number,
  b_8: Number,
  a_9: Number,
  b_9: Number,
  a_10: Number,
  b_10: Number,
  a_11: Number,
  b_11: Number,
  a_12: Number,
  b_12: Number
});

module.exports =  mongoose.model('Answer', answerSchema);